version: '3.8'

networks:
  web:
    external: false
  internal:
    external: false

services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: always
    ports:
      - '3000:3000'
    volumes:
      - ./grafana_data:/var/lib/grafana
    networks:
      - web
      - internal

  influxdb:
    image: influxdb:2.7
    container_name: influxdb
    restart: always
    ports:
      - '8086:8086'
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=adminpass
      - DOCKER_INFLUXDB_INIT_ORG=demoorg
      - DOCKER_INFLUXDB_INIT_BUCKET=adatok
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=admintoken
    volumes:
      - ./influxdb_data:/var/lib/influxdb2
    networks:
      - internal

  jupyter:
    image: jupyter/base-notebook
    container_name: jupyter
    restart: always
    user: '0'
    ports:
      - '8888:8888'
    volumes:
      - ./jupyter_notebooks:/home/jovyan/work
    networks:
      - web
      - internal